### ISSUE TITLE
Celo Governance Call #21 | August 25th, 2022

### ISSUE THREAD

**Issue by willkraft** [celo-org/governance#164]
# Celo Governance Call #21

![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)

When: August 25th, 2022. 12 PM ET / 9 AM PT 60 minutes max
Where: meet.google.com/omh-ridi-iwb

## Agenda
* [Introduce new StableCoin pegged to Colombian Peso - $cCOP](https://github.com/celo-org/governance/blob/603445c05f8444ae63e13c9d0fdceffecc5c7c95/CGPs/cgp-0060.md)
* [Celo Core Contracts Release 8](https://github.com/celo-org/governance/blob/0xarthurxyz/cgp-61-core-contracts-8/CGPs/cgp-0061.md)
* Process for getting in touch with approvers

_Please post all relevant proposals below that should be discussed and evaluated_

**Comment by willkraft** [comment]
Hi all, please see notes from the call [here](https://docs.google.com/document/d/1F6rozEJ90sjF5Bwm2qt6vNW2mrLLHf3kPfTqhvl9StM/edit?usp=sharing)

**Comment by willkraft** [comment]
@m-chrzan do you guys want to discuss Core Contracts Release 8?

**Comment by 0xarthurxyz** [comment]
> @m-chrzan do you guys want to discuss Core Contracts Release 8?

Hey @willkraft, thanks for asking!
Yes please, that would be great :100:

Some more context:

- Core Contracts Release 8 only includes identity related contract changes, which is why I'm taking an active role in this release process (as part of cLabs identity team). 
- We haven't completely finished writing the [release notes](https://github.com/celo-org/celo-monorepo/releases/tag/core-contracts.v8.pre-audit), but the main audit is complete ([report](https://hacken.io/wp-content/uploads/2022/08/CLABS_04072022_SCAudit_Report2-5.pdf)).

Would you be able to provide more context on the type of information we would ideally present at the meeting, to gauge whether we'll be ready by Thursday? 

Thanks in advance!

**Comment by willkraft** [comment]
@0xarthurxyz Perfect, I added to the agenda! For the discussion, generally there's a description of the changes that would be made by the proposal and why it's needed - we aim to keep it under 5 min, and it doesn't have to be too formal. Even if not everything is ready, as long as the changes the proposal would make are relatively finalized, that's enough to discuss it

**Comment by willkraft** [comment]
Hi all, please see [here](https://docs.google.com/document/d/1SCYuX8UxafFhQ1tcLXCtp5bbdPjdN49Dz58HruegGCU/edit#) for the notes and [here](https://drive.google.com/file/d/1iEtteo3Nze7qM1eGJIcmxAZAtedQQ3Or/view) for the recording
